name: GraalVM build
on:
  push:
    branches: [ "[1-9]+.[0-9]+.x" ]
  pull_request:
    branches: [ "[1-9]+.[0-9]+.x" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1.2.6 # https://github.com/graalvm/setup-graalvm
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Echo Java and Native Image version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Native Compile
        run: ./gradlew nativeCompile
      - name: Native Test
        run: ./gradlew nativeCompile